spring:
  application:
    name: shopeasy
  datasource:
    url: jdbc:mariadb://localhost:3306/shopeasy_db
    username: shopeasy_user
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # En prod mettre 'validate'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  # Configuration de la validation
  web:
    resources:
      add-mappings: false

# Configuration JWT
jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  access-token:
    expiration: 900000 # 15 minutes
  refresh-token:
    expiration: 604800000 # 7 jours
    max-per-user: 5 # Nombre maximum de refresh tokens actifs par utilisateur

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

server:
  servlet:
    context-path: /api/v1
  port: 8080


# OpenAPI Configuration
shopeasy:
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://api.shopeasy.com

# SpringDoc Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true

  packages-to-scan: com.shopeasy.shopeasy.controller
  paths-to-match: /api/v1/**
  paths-to-exclude: /actuator/**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json